[SDL2]
src.github_tag = "libsdl-org/SDL"
fetch.github = "libsdl-org/SDL"
src.include_regex = "release-2.*"

[SDL2_android]
src.github_tag = "libsdl-org/SDL"
fetch.github = "libsdl-org/SDL"
src.include_regex = "release-2.0.18"

[SDL2_mixer]
src.github = "libsdl-org/SDL_mixer"
fetch.github = "libsdl-org/SDL_mixer"
src.include_regex = "release-2.*"

[enet]
src.git = "https://github.com/lsalzman/enet"
fetch.git = "https://github.com/lsalzman/enet"

[wavpack]
src.github = "dbry/WavPack"
fetch.github = "dbry/WavPack"

[libvorbis]
src.github = "xiph/vorbis"
fetch.github = "xiph/vorbis"

[opusfile]
src.git = "https://github.com/xiph/opusfile"
fetch.git = "https://github.com/xiph/opusfile"

[openal]
src.github = "kcat/openal-soft"
fetch.github = "kcat/openal-soft"

[openal_android]
src.github_tag = "kcat/openal-soft"
fetch.github = "kcat/openal-soft"
src.include_regex = "1.22.2"

[libmpg123]
src.git = "https://github.com/madebr/mpg123"
fetch.git = "https://github.com/madebr/mpg123"

[libmodplug]
src.git = "https://github.com/Konstanty/libmodplug"
fetch.git = "https://github.com/Konstanty/libmodplug"

[libxmp]
src.github = "libxmp/libxmp"
fetch.github = "libxmp/libxmp"

[libopus]
src.github = "xiph/opus"
fetch.github = "xiph/opus"

[libogg]
src.github = "xiph/ogg"
fetch.github = "xiph/ogg"

[game-music-emu]
src.github_tag = "libgme/game-music-emu"
fetch.github = "libgme/game-music-emu"
# Doesn't work with 0.6.4+ for now
src.include_regex = "0.6.3"

[fluidsynth]
src.git = "https://github.com/chirs241097/fluidsynth-sans-glib"
fetch.git = "https://github.com/chirs241097/fluidsynth-sans-glib"
src.branch = "patched"

[miniupnpc]
src.github_tag = "miniupnp/miniupnp"
fetch.github = "miniupnp/miniupnp"
# Bindings in Doom2D Forever are for this version
src.include_regex = "miniupnpc_2_2_6"

[fpc]
src.git = "https://gitlab.com/freepascal.org/fpc/source"
fetch.git = "https://gitlab.com/freepascal.org/fpc/source"

[lazarus]
src.git = "https://gitlab.com/freepascal.org/lazarus/lazarus"
fetch.git = "https://gitlab.com/freepascal.org/lazarus/lazarus"