# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  SDL2 = {
    pname = "SDL2";
    version = "release-2.32.6";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL";
      rev = "release-2.32.6";
      fetchSubmodules = false;
      sha256 = "sha256-sXlW+ivDRCNMcZDzZEfOPGvFGU0aE4n/fO+Wxym6GGw=";
    };
  };
  SDL2_android = {
    pname = "SDL2_android";
    version = "release-2.0.18";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL";
      rev = "release-2.0.18";
      fetchSubmodules = false;
      sha256 = "sha256-R7MBR3QoXwR4Pg0YasSkwwyPTPOQLdgj6KJfyQKAKoc=";
    };
  };
  SDL2_mixer = {
    pname = "SDL2_mixer";
    version = "release-2.8.1";
    src = fetchFromGitHub {
      owner = "libsdl-org";
      repo = "SDL_mixer";
      rev = "release-2.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-6HOTLwGi2oSQChwHE/oNHfZpcMh8xTuwNQSpKS01bwI=";
    };
  };
  enet = {
    pname = "enet";
    version = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
    src = fetchgit {
      url = "https://github.com/lsalzman/enet";
      rev = "657eaf97d9d335917c58484a4a4b5e03838ebd8e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-JIvasudVSQjWttg9fockmyJbGPrQe1hzsQRChpDzW8c=";
    };
    date = "2024-11-14";
  };
  fluidsynth = {
    pname = "fluidsynth";
    version = "209f46745a4cca9bf6367fae11920c7bce3b9681";
    src = fetchgit {
      url = "https://github.com/chirs241097/fluidsynth-sans-glib";
      rev = "209f46745a4cca9bf6367fae11920c7bce3b9681";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-NZ6Fe5Tj3BTQw6yEggJL4IfhX/MOuGtQLJfltJuUDMo=";
    };
    date = "2021-11-07";
  };
  fpc = {
    pname = "fpc";
    version = "e2d58b8b944227a6b1911c62bb59cbc686da0ac2";
    src = fetchgit {
      url = "https://gitlab.com/freepascal.org/fpc/source";
      rev = "e2d58b8b944227a6b1911c62bb59cbc686da0ac2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-+sM7V+RK4d3N/K94+50EfErIch/5OjSW2WtbQLY1xj4=";
    };
    date = "2025-05-12";
  };
  game-music-emu = {
    pname = "game-music-emu";
    version = "0.6.3";
    src = fetchFromGitHub {
      owner = "libgme";
      repo = "game-music-emu";
      rev = "0.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-XmPcFfKsEe07hH7f0xMs9hRJshOO/p58Zm9fYsmCCoA=";
    };
  };
  lazarus = {
    pname = "lazarus";
    version = "8fb7e576945c0fb4dbad4029cfa8d85222c35007";
    src = fetchgit {
      url = "https://gitlab.com/freepascal.org/lazarus/lazarus";
      rev = "8fb7e576945c0fb4dbad4029cfa8d85222c35007";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-vODUlp9pN+3Qnh5qPxiHs37G1REM6VpQJeUMTCfq9L4=";
    };
    date = "2025-05-12";
  };
  libmodplug = {
    pname = "libmodplug";
    version = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
    src = fetchgit {
      url = "https://github.com/Konstanty/libmodplug";
      rev = "d1b97ed0020bc620a059d3675d1854b40bd2608d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-wBOAbCLUExdU+rg5NSghC8QXlMwsYBUkt2EsEvFKMug=";
    };
    date = "2022-01-31";
  };
  libmpg123 = {
    pname = "libmpg123";
    version = "34fe0b4173da7afcbb9e75d4132437653bc42a29";
    src = fetchgit {
      url = "https://github.com/madebr/mpg123";
      rev = "34fe0b4173da7afcbb9e75d4132437653bc42a29";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-8LP3Ic8IYNAxwVghJEluV/flY0NABU1Trgqxqm+FgJo=";
    };
    date = "2025-04-21";
  };
  libogg = {
    pname = "libogg";
    version = "v1.3.5";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "ogg";
      rev = "v1.3.5";
      fetchSubmodules = false;
      sha256 = "sha256-ync2np86Nje1R/g41VLhPhsld+yLZ40Pxv1wNzWCtss=";
    };
  };
  libopus = {
    pname = "libopus";
    version = "v1.5.2";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "opus";
      rev = "v1.5.2";
      fetchSubmodules = false;
      sha256 = "sha256-M1G7ypcfs7nJmXgkyoG96jT/CkgN5BOzy+DGO4LVCvA=";
    };
  };
  libvorbis = {
    pname = "libvorbis";
    version = "v1.3.7";
    src = fetchFromGitHub {
      owner = "xiph";
      repo = "vorbis";
      rev = "v1.3.7";
      fetchSubmodules = false;
      sha256 = "sha256-yCnbAxkbZN674F5HVd+DTmotvdtYnkJiO01B6foOiVY=";
    };
  };
  libxmp = {
    pname = "libxmp";
    version = "libxmp-4.6.3";
    src = fetchFromGitHub {
      owner = "libxmp";
      repo = "libxmp";
      rev = "libxmp-4.6.3";
      fetchSubmodules = false;
      sha256 = "sha256-VTjS5bVu+jiswP4GCTxcAdhtVdtopy4A3hxlzIQlZVU=";
    };
  };
  miniupnpc = {
    pname = "miniupnpc";
    version = "miniupnpc_2_2_6";
    src = fetchFromGitHub {
      owner = "miniupnp";
      repo = "miniupnp";
      rev = "miniupnpc_2_2_6";
      fetchSubmodules = false;
      sha256 = "sha256-UropqH4YNR42R7L03ROx2j6Sq5RcqQ/64VYb2GcCkY8=";
    };
  };
  openal = {
    pname = "openal";
    version = "1.24.3";
    src = fetchFromGitHub {
      owner = "kcat";
      repo = "openal-soft";
      rev = "1.24.3";
      fetchSubmodules = false;
      sha256 = "sha256-VQa3FD9NyvDv/+VbU+5lmV0LteiioJHpRkr1lnCn1g4=";
    };
  };
  openal_android = {
    pname = "openal_android";
    version = "1.22.2";
    src = fetchFromGitHub {
      owner = "kcat";
      repo = "openal-soft";
      rev = "1.22.2";
      fetchSubmodules = false;
      sha256 = "sha256-MVM0qCZDWcO7/Hnco+0dBqzBLcWD279xjx0slxxlc4w=";
    };
  };
  opusfile = {
    pname = "opusfile";
    version = "d2535e62809079c81f9e5139c0daebe43af97be4";
    src = fetchgit {
      url = "https://github.com/xiph/opusfile";
      rev = "d2535e62809079c81f9e5139c0daebe43af97be4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [];
      sha256 = "sha256-/vktWxWfxiQcn3t+zhGainIQINywA/FatFIRsrwvmoI=";
    };
    date = "2025-04-19";
  };
  wavpack = {
    pname = "wavpack";
    version = "5.8.1";
    src = fetchFromGitHub {
      owner = "dbry";
      repo = "WavPack";
      rev = "5.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-V9jRIuDpZYIBohJRouGr2TI32BZMXSNVfavqPl56YO0=";
    };
  };
}
