name: Build toolchains

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
      - name: Build fpc-3_2_2
        run: |
          nix build --inputs-from . --verbose --show-trace --print-build-logs --print-out-paths nixpkgs#hello
      - name: Save Nix store
        uses: nix-community/cache-nix-action/save@v5.1.0
        with:
          primary-key: build-${{ runner.os }}-${{ hashFiles('flake.nix') }}