name: Checks

on:
  workflow_dispatch:

jobs:
  nix-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run Nix checks
        id: set-matrix
        run: |
          nix flake update d2df-sdl d2df-editor doom2df-res
          nix flake check