name: CI

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update Doom2D related inputs
        run: |
          nix flake update d2df-sdl doom2df-res
      - name: Build debug APK
        run: |
          nix build .#legacyPackages.x86_64-linux.android.doom2df-sdl2_mixer-apk
      - uses: actions/upload-artifact@v4
        with:
          name: doom2df-android
          path: result/bin/d2df.signed.apk
          if-no-files-found: error
      - name: Build Windows 32-bit ZIP bundle
        run: |
          nix build .#legacyPackages.x86_64-linux.mingw.byArch.mingw32.doom2df-bundle
      - uses: actions/upload-artifact@v4
        with:
          name: doom2df-win32
          path: result
          if-no-files-found: error