name: CI

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v29
      - name: Remove unnecessary packages
        run: | # stolen from https://github.com/easimon/maximize-build-space
          echo "=== Before pruning ==="
          df -h
          sudo rm -rf /opt || true
          echo
          echo "=== After pruning ==="
          df -h
      # To make the environment in the flake's devShell available to future steps:
      - uses: rrbutani/use-nix-shell-action@v1
        with:
          devShell: .#default
      - name: Calculate cache hash based on nixpkgs' revision
        run: |
          NIXPKGS_REV=$(nix flake metadata . --json 2>/dev/null | jq --raw-output '.locks.nodes."nixpkgs".locked.rev')
          echo "NIXPKGS_REV=$NIXPKGS_REV" >> "$GITHUB_ENV"            
      - uses: nix-community/cache-nix-action/restore@v5.1.0
        with:
          primary-key: build-fpc-${{ runner.os }}-${{ env.NIXPKGS_REV }}
          fail-on: primary-key.miss        
      - name: Update Doom2D related inputs and populate environment variables
        run: |
          bash ./game/bundle/scripts/mkEnv.bash
      - name: Build debug APK
        run: |
          bash ./game/bundle/scripts/mkAndroid.bash
      - uses: actions/upload-artifact@v4
        with:
          name: doom2df-android
          path: result
          if-no-files-found: error
      - name: Build Windows 32-bit ZIP bundle
        env:
          D2DF_LAST_COMMIT_DATE: ${{ env.D2DF_LAST_COMMIT_DATE }}
          RES_LAST_COMMIT_DATE: ${{ env.RES_LAST_COMMIT_DATE }}
          EDITOR_LAST_COMMIT_DATE: ${{ env.D2DF_LAST_COMMIT_DATE }}
        run: |
          bash ./game/bundle/scripts/mkZip.bash
      - uses: actions/upload-artifact@v4
        with:
          name: doom2df-win32
          path: doom2df-win32.zip
          if-no-files-found: error
      - uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
        with:
          artifacts: doom2df-win32.zip, doom2df-android.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Doom2D Forever builds (latest commit)
          bodyFile: release_body
          tag: doom2dforever
          allowUpdates: true
          artifactErrorsFailBuild: true
          prerelease: true
          replacesArtifacts: true