name: CI

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update Doom2D related inputs
        run: |
          nix flake update d2df-sdl doom2df-res
      - name: Build debug APK
        run: |
          nix build .#legacyPackages.x86_64-linux.android.doom2df-sdl2_mixer-apk
          cp result doom2df-android.apk
      - uses: actions/upload-artifact@v4
        with:
          name: doom2df-android
          path: result
          if-no-files-found: error
      - name: Build Windows 32-bit ZIP bundle
        run: |
          nix build .#legacyPackages.x86_64-linux.mingw.byArch.mingw32.doom2df-bundle
          nix run nixpkgs#zip -- -r doom2df-win32.zip result
      - uses: actions/upload-artifact@v4
        with:
          name: doom2df-win32
          path: result
          if-no-files-found: error
      - uses: ncipollo/release-action@v1
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
        with:
          artifacts: doom2df-win32.zip, doom2df-android.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Doom2D Forever builds (latest commit)
          tag: doom2dforever
          allowUpdates: true
          artifactErrorsFailBuild: true
          prerelease: true
          replacesArtifacts: true